name: Daily X Screenshot

on:
  schedule:
    - cron: '0 20 * * *'  # Every day at 6am AEST (8pm UTC)
  workflow_dispatch:        # Manual trigger option

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create screenshots folder
        run: mkdir -p screenshots

      - name: Download screenshot using ScreenshotOne
        env:
          API_KEY: ${{ secrets.SCREENSHOTONE_API_KEY }}
        run: |
          DATE=$(date +'%Y-%m-%d')
          mkdir -p screenshots
          curl "https://api.screenshotone.com/take?access_key=$API_KEY&url=https://x.com/DrBinLu&full_page=true&delay=5000" \
            --output "screenshots/x-${DATE}.png"

      - name: Commit and push screenshot
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add screenshots/
          git commit -m "Add screenshot for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
